let exercise_list = [
    {
        id: "A1",
        title: "Jump the Rope",
        unity: " min",
        image: "./Images/1_warmup/A1.svg",
        description: "Jump the rope or jumping jack for 10 minutes.",
        type: "warmup",
        sets: 1,
    },
    {
        id: "A2",
        title: "Shoulder Rotations",
        unity: " reps",
        image: "./Images/1_warmup/A2.svg",
        description: "Ten Shoulder rotations.",
        type: "warmup",
        sets: 1,
    },
    {
        id: "A3",
        title: "Arm Raises",
        unity: " reps",
        image: "./Images/1_warmup/A3.svg",
        description: "Ten Arm raises.",
        type: "warmup",
        sets: 1,
    },
    {
        id: "A4",
        title: "Torso Rotations",
        unity: " reps",
        image: "./Images/1_warmup/A4.svg",
        description: "Ten Torso Rotations.",
        type: "warmup",
        sets: 1,
    },
    {
        id: "A5",
        title: "Chest Expansions",
        unity: " reps",
        image: "./Images/1_warmup/A5.svg",
        description: "Ten Chest expansions, with palms facing upwards.",
        type: "warmup",
        sets: 1,
    },
    {
        id: "A6",
        title: "Neck Rotations",
        unity: " reps",
        image: "./Images/1_warmup/A6.svg",
        description: "Rotate your neck slowly. Each rotation should take at least four seconds.",
        type: "warmup",
        sets: 1,
    },
    {
        id: "A7",
        title: "Hip Rotations - Left",
        unity: " reps",
        image: "./Images/1_warmup/A7.svg",
        description: "Ten Hip rotations to the left.",
        type: "warmup",
        sets: 1,
    },
    {
        id: "A8",
        title: "Hip Rotations - Right",
        unity: " reps",
        image: "./Images/1_warmup/A8.svg",
        description: "Ten Hip rotations to the right.",
        type: "warmup",
        sets: 1,
    },
    {
        id: "A9",
        title: "Reverse Hip Rotations - Left",
        unity: " reps",
        image: "./Images/1_warmup/A9.svg",
        description: "Ten Reverse Hip rotations to the left.",
        type: "warmup",
        sets: 1,
    },
    {
        id: "A10",
        title: "Reverse Hip Rotations - Right",
        unity: " reps",
        image: "./Images/1_warmup/A10.svg",
        description: "Ten Reverse Hip rotations to the right.",        
        type: "warmup",
        sets: 1,
    },
    {
        id: "A11",
        title: "Front Leg Raises - Left",
        unity: " reps",
        image: "./Images/1_warmup/A11.svg",
        description: "Ten Front leg raises to the left.",
        type: "warmup",
        sets: 1,
    },
    {
        id: "A12",
        title: "Front Leg Raises - Right",
        unity: " reps",
        image: "./Images/1_warmup/A12.svg",
        description: "Ten Front leg raises to the right.",
        type: "warmup",
        sets: 1,
    },
    {
        id: "B01",
        title: "Squat",
        unity: " reps",
        image: "./Images/2_chalistenics/B1.svg",
        description: "30x 3_reps. Description Not Needed",
        type: "workout",
        sets: 3,
    },
    {
        id: "B02",
        title: "Chin Ups",
        unity: " reps",
        image: "./Images/2_chalistenics/B2.svg",
        description: "8x 3_reps. Description Not Needed",
        type: "workout",
        sets: 3,
    },
    {
        id: "B03",
        title: "Handstand Push Ups",
        unity: " reps",
        image: "./Images/2_chalistenics/B3.svg",
        description: "8x 3_reps. Description Not Needed",
        type: "workout",
        sets: 3,
    },
    {
        id: "B04",
        title: "Leg Raises",
        unity: " reps",
        image: "./Images/2_chalistenics/B4.svg",
        description: "8x 3_reps. Description Not Needed",
        type: "workout",
        sets: 3,
    },
    {
        id: "B05",
        title: "Push Ups - Finger Hold",
        unity: " reps",
        image: "./Images/2_chalistenics/B5.svg",
        description: "8x. Description Not Needed",
        type: "workout",
        sets: 1,
    },
    {
        id: "B06",
        title: "Push Ups - Closed Fist",
        unity: " reps",
        image: "./Images/2_chalistenics/B6.svg",
        description: "8x. Description Not Needed",
        type: "workout",
        sets: 1,
    },
    {
        id: "B07",
        title: "Push Ups - Diamond",
        unity: " reps",
        image: "./Images/2_chalistenics/B7.svg",
        description: "8x. Description Not Needed",
        type: "workout",
        sets: 3,
    },
    {
        id: "B08",
        title: "Pull Ups",
        unity: " reps",
        image: "./Images/2_chalistenics/B8.svg",
        description: "8x 3_reps. Description Not Needed",
        type: "workout",
        sets: 3,
    },
    {
        id: "B09",
        title: "Dips",
        unity: " reps",
        image: "./Images/2_chalistenics/B9.svg",
        description: "8x 3_reps. Description Not Needed",
        type: "workout",
        sets: 3,
    },
    {
        id: "B10",
        title: "Pelvis Elevation",
        unity: " reps",
        image: "./Images/2_chalistenics/B10.svg",
        description: "8x 3_reps. Description Not Needed",
        type: "workout",
        sets: 3,
    },
    {
        id: "B11",
        title: "Horizontal Plank",
        unity: " segs",
        image: "./Images/2_chalistenics/B11.svg",
        description: "60 seconds. Description Not Needed",
        type: "workout",
        sets: 1,
    },
    {
        id: "B12",
        title: "Left-Sided Plank",
        unity: " segs",
        image: "./Images/2_chalistenics/B12.svg",
        description: "60 seconds. Description Not Needed",
        type: "workout",
        sets: 1,
    },
    {
        id: "B13",
        title: "Right-Sided Plank",
        unity: " segs",
        image: "./Images/2_chalistenics/B13.svg",
        description: "60 seconds. Description Not Needed",
        type: "workout",
        sets: 1,
    },
    {
        id: "B14",
        title: "Glute Kickback",
        unity: " reps",
        image: "./Images/2_chalistenics/B14.svg",
        description: "8x 3_reps. Description Not Needed",
        type: "workout",
        sets: 3,
    },
    {
        id: "B15",
        title: "Hand Grip Training",
        unity: " reps",
        image: "./Images/2_chalistenics/B15.svg",
        description: "3_reps until failure.",
        type: "workout",
        sets: 3,
    },
    {
        id: "B16",
        title: "Neck Bridge",
        unity: " reps",
        image: "./Images/2_chalistenics/B16.svg",
        description: "3_reps until failure.",
        type: "workout",
        sets: 1,
    },
    {
        id: "B17",
        title: "Lying Neck-rotation",
        unity: " reps",
        image: "./Images/2_chalistenics/B17.svg",
        description: "Until failure",
        type: "workout",
        sets: 1,
    },
    {
        id: "B18",
        title: "Side Neck Curls",
        unity: " reps",
        image: "./Images/2_chalistenics/B18.svg",
        description: "Until failure",
        type: "workout",
        sets: 1,
    },
    {
        id: "B19",
        title: "Forward Flexion Neck-stretch",
        unity: " reps",
        image: "./Images/2_chalistenics/B19.svg",
        description: "Until failure",
        type: "workout",
        sets: 1,
    },
    {
        id: "B20",
        title: "Prone Cervical Extension",
        unity: " reps",
        image: "./Images/2_chalistenics/B20.svg",
        description: "Until failure",
        type: "workout",
        sets: 1,
    },
    {
        id: "C01",
        title: "Neck Benders",
        unity: " segs",
        image: "./Images/3_stretching/C01.svg",
        description: "30s. Tilt head to the side toward one shoulder. Do with the other side as well.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C02",
        title: "Neck Rotators",
        unity: " segs",
        image: "./Images/3_stretching/C02.svg",
        description: "30s. Turn head slowly to look over one shoulder. Do with both sides.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C03",
        title: "Arms Biceps",
        unity: " segs",
        image: "./Images/3_stretching/C03.svg",
        description: "30s. With arms straight and fingers interlaced behind back, raise hands toward ceiling.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C04",
        title: "Arms Triceps",
        unity: " segs",
        image: "./Images/3_stretching/C04.svg",
        description: "30s. Bend elbow and place hand of bent arm on back of neck. Using the other hand, pull elbow behind head.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C05",
        title: "Arms Wrist Flexors - Left",
        unity: " segs",
        image: "./Images/3_stretching/C05.svg",
        description: "30s. Stretch arm out in front with elbow straight and palm facing away. With other hand, pull fingers backward.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C06",
        title: "Arms Wrist Flexors - Right",
        unity: " segs",
        image: "./Images/3_stretching/C06.svg",
        description: "30s. Right Side Now.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C07",
        title: "Neck Trapezius - Left",
        unity: " segs",
        image: "./Images/3_stretching/C07.svg",
        description: "30s. Tilt head to left side. With arms behind back, use left hand to pull right arm over and down to the left.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C08",
        title: "Neck Trapezius - Right",
        unity: " segs",
        image: "./Images/3_stretching/C08.svg",
        description: "30s. Right Side Now.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C09",
        title: "Shoulders Deltoid/Rhomboids - Right",
        unity: " segs",
        image: "./Images/3_stretching/C09.svg",
        description: "30s. Pull right arm across chest with left hand. Turn head away from pull.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C10",
        title: "Shoulders Deltoid/Rhomboids - Left",
        unity: " segs",
        image: "./Images/3_stretching/C10.svg",
        description: "30s. Left arm now.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C11",
        title: "Core Oblique/Intercostals - Right",
        unity: " segs",
        image: "./Images/3_stretching/C11.svg",
        description: "30s. Stand erect with hands overhead and palms together. Bend the body to the right side.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C12",
        title: "Core Oblique/Intercostals - Left",
        unity: " segs",
        image: "./Images/3_stretching/C12.svg",
        description: "30s. Left Side now.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C13",
        title: "Chest Pecs",
        unity: " segs",
        image: "./Images/3_stretching/C13.svg",
        description: "30s. Grab both sides of doorway one inch below shoulder height. Lean forward until stretch is felt in chest. Keep back straight and feet shoulder-width apart.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C14",
        title: "Legs Calves - Right",
        unity: " segs",
        image: "./Images/3_stretching/C14.svg",
        description: "30s. Place hands on wall and stagger feet two to three feet apart. Keep right leg straight with heel on floor. Lean into the wall with left foot close to the wall until stretch is felt in calf.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C15",
        title: "Legs Calves - Left",
        unity: " segs",
        image: "./Images/3_stretching/C15.svg",
        description: "30s. Left leg now.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C16",
        title: "Legs Achilles/Soleus - Right",
        unity: " segs",
        image: "./Images/3_stretching/C16.svg",
        description: "30s. Place hands on wall and stagger feet one to two feet apart. Keep back right leg slightly bent with heel on floor. Lean into wall until a stretch is felt in Achilles.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C17",
        title: "Legs Achilles/Soleus - Left",
        unity: " segs",
        image: "./Images/3_stretching/C17.svg",
        description: "30s. Left leg now.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C18",
        title: "Hip Abductors - Right",
        unity: " segs",
        image: "./Images/3_stretching/C18.svg",
        description: "30s. Cross right leg behind the left. Lean right hip toward wall while bending left knee. Keep right knee straight.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C19",
        title: "Hip Abductors - Left",
        unity: " segs",
        image: "./Images/3_stretching/C19.svg",
        description: "30s. Repeat with left leg behind right.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C20",
        title: "Legs Quadriceps - Right",
        unity: " segs",
        image: "./Images/3_stretching/C20.svg",
        description: "30s. Lie on side with knees bent and hold top foot with same-side hand. Pull heel in toward buttock, keeping knees in line and hip pressed forward.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C21",
        title: "Legs Quadriceps - Left",
        unity: " segs",
        image: "./Images/3_stretching/C21.svg",
        description: "30s. Left Side now.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C22",
        title: "Back Lumbar Extensors - Right",
        unity: " segs",
        image: "./Images/3_stretching/C22.svg",
        description: "30s. Grasp hands underneath knee joint of right leg and bring knee to chest.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C23",
        title: "Back Lumbar Extensors - Left",
        unity: " segs",
        image: "./Images/3_stretching/C23.svg",
        description: "30s. Repeat with other leg.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C24",
        title: "Legs Hamstrings",
        unity: " segs",
        image: "./Images/3_stretching/C24.svg",
        description: "30s. With head raised up and lower back slightly arched, tuck chin to chest and round back toward ceiling. Hold the arched and round back positions briefly.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C25",
        title: "Hip Internal Rotators - Right",
        unity: " segs",
        image: "./Images/3_stretching/C25.svg",
        description: "30s. Lie on back and gently pull right foot and knee toward right shoulder.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C26",
        title: "Hip Internal Rotators - Left",
        unity: " segs",
        image: "./Images/3_stretching/C26.svg",
        description: "30s. Left side now.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C27",
        title: "Legs Groin",
        unity: " segs",
        image: "./Images/3_stretching/C27.svg",
        description: "30s. Place soles of feet flat together. Gently lean forward and push down on knees with forearms.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C28",
        title: "Legs Adductors/Groin",
        unity: " segs",
        image: "./Images/3_stretching/C28.svg",
        description: "30s. With legs apart, knees straight and back straight, slide hands forward.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C29",
        title: "Hip External Rotators - Left",
        unity: " segs",
        image: "./Images/3_stretching/C29.svg",
        description: "30s. Place left leg over right and bring right arm to the outside of left leg. Press left leg across body with right elbow. Turn head and look over left shoulder.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C30",
        title: "Hip External Rotators - Right",
        unity: " segs",
        image: "./Images/3_stretching/C30.svg",
        description: "30s. Right Side Now.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "C31",
        title: "Neck on Wall",
        unity: " segs",
        image: "./Images/3_stretching/C31.svg",
        description: "For 1 minute, stretch your neck against the wall.",
        type: "stretching",
        sets: 1,
    },
    {
        id: "D01",
        title: "Breathing Exercise",
        unity: " reps",
        image: "./Images/4_postWorkout/D01.svg",
        description: "The method stimulates the nervous system, improves circulation, and increases energy. It involves deep, controlled breaths followed by full exhales, repeated several times.",
        type: "extra",
        sets: 1,
    },
    {
        id: "D02",
        title: "Prayer",
        unity: " reps",
        image: "./Images/4_postWorkout/D02.svg",
        description: "[Description to be added]",
        type: "extra",
        sets: 1,
    }
]
